spring:

  datasource:
    url: jdbc:mysql://localhost:3307/supply_chain_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      max-lifetime: 300000
      idle-timeout: 30000
      leak-detection-threshold: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    http:
      path: /graphql

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/supply-chain
          jwk-set-uri: http://localhost:8082/realms/supply-chain/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: supply-chain-client
      principle-attribute: preferred_username

server:
  port: 8080

logging:
  level:
    com.supplychainx: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
